### ISSUE TITLE
Discovery: Determine feasibility/work to move off CKAN 2.3 fork and onto upstsream CKAN core

### ISSUE THREAD

**Issue by estebanruseler** [GSA/datagov-ckan-multi#257]
## Description

This is a timeboxed effort to understand the technical implications of, and determine the HL level of effort involved in, moving collections away from the approach taken before with the catalog-app (ie amending CKAN core) to using the OKF upstream version of CKAN 2.8 and then creating extensions for any additional features required (eg collections. 

This has two parts:
1.  [Discovery: Determine work to move collections out of GSA CKAN core and into an extension](https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-deploy/1461)
2. Determine the work involved of anything else that is currently in the CKAN 2.3 fork that we would need to move out into an extension(s). 

The following is an acceptance criteria for the second part:

## Acceptance Criteria
- [ ]  We have a summary of "non-core code" in the CKAN 2.3 fork. I.e. BSP config and the "Features that CKAN is missing that should be extensions", Is there anything else?
 - [ ] We have an estimate for the work involved to create an extension (or add to an existing extension) the non-code in CKAN core (apart from Collections and BSP config) if there is any

## Details / tasks
- [ ] Investigate "non-core code" in the catalog app and summarize; ie BSP config, collections, "Features that CKAN is missing that should be extensions", what else? (the BSP config we can somewhat ignore because GSA will be moving to cloud.gov)
- [ ] tbc based on the above. If there is no "bespoke" code apart from BSP config and collections then happy days. If there is additional code then we need to understand the feature and see how we could better deal with it in an extension

**Comment by kimwdavidson** [comment]
@adborden to add notes and close

**Comment by adborden** [comment]
@estebanruseler from our discussion this morning, I think I miss understood the difference between this issue and https://github.com/gsa/datagov-ckan-multi/issues/259. Sounds like https://github.com/gsa/datagov-ckan-multi/issues/259 is really just about a vanilla CKAN 2.8 based on okfn, is that correct?

And then this issue is about understanding the [GSA/ckan fork](https://github.com/GSA/ckan) and how to apply those commits on top of https://github.com/gsa/datagov-ckan-multi/issues/259, whether as patches to CKAN, submitting PRs, or using new/existing extensions. Is that right?

If that's the case, then I think we just want to change the title, "Discovery: Determine feasibility/work to move off catalog's CKAN fork onto upstsream CKAN core" and this is still work that needs to be done.

**Comment by estebanruseler** [comment]
@adborden Okay, I hope taking a step back helps. The big picture is that we want to get off GSA's old catalog fork so we need to build an extension for the collections. But, according to the [pre-analysis doc](https://docs.google.com/document/d/1ZkRXFfHrlWYyTs7fQnfzNhHT4_amzyUgM5m0qrT_RXg/edit?ts=5e724f6e#) we know there is other custom code (ie any non-native to CKAN core), viz.:
> Changes to support collections
Changes for the BSP environment
Features that CKAN is missing that should be extensions
    * Extensions can’t integrate with search, though

Now we can ignore the BSP environment for now as this should be better handled elsewhere (at worst a hot patch but anywhere is better than CKAN core) so the outstanding question is - is there any other code we need to incorporate in an existing or new extension so when we migrate off your GSA fork, s'all good. 

For me, this is part of the discovery ticket (it was originally but then Julie wanted it broken out), and we should be understanding this before starting to architect or code the collections extension (to be on the safe side). So I suggested to Julie that she do this first. 

Anyway, this is td;lr. Basically, if you know what this non-core code is and where it lives please with us so that as we are re-building catalog app on firmer 2.8 ground we make sure everything you are expecting in the new catalog app has all the features as the old one minus the headaches.

**Comment by adborden** [comment]
@estebanruseler let's try to sync up on this tomorrow. I don't understand if this issue is about [catalog-app](https://github.com/GSA/catalog-app), the [CKAN fork](https://github.com/GSA/ckan/tree/datagov), or the new [ckanext-collections](https://github.com/GSA/ckanext-collections).

**Comment by estebanruseler** [comment]
Link to Julie's analysis https://docs.google.com/spreadsheets/d/1nFJyKfGobIEi1v-UEGmdvKSVNIe1QFW61L7HwzJLDTY/edit#gid=0

**Comment by adborden** [comment]
@thejuliekramer I really appreciate the spreadsheet and the commit-by-commit analysis, well done!

The created issues capture the outcome of this analysis well. However, I'd prefer we write these stories more like features. For example, the story is less about moving commits to extensions or upstream and more about implementing a feature "the right way". I've updated https://github.com/GSA/datagov-ckan-multi/issues/270#issue-604160987 to include a user story and AC that better captures the value we're providing to the user. This is important because it will help us prioritize the work based on user value. We can update the stories as we groom them, so I'm going to call this story done. Thanks!
