### ISSUE TITLE
Integration with the existing deployment tool

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#286]
## User Story

As a data.gov developer, I want the existing deploy tool to deploy the new catalog app with all of its required configuration and dependencies so that I can reliably deploy the new catalog app application along with the existing platform.

## Acceptance Criteria
WHEN I run the datagov-deploy tool
- [x] THEN I can visit the new catalog app at the environment's URL.

## Details / tasks
- [x] generate a requirements.txt that can be used by datagov-deploy
- [x] update ansible files for 2.8
- [x] document guidelines for keeping catalog-next deployable
- [x] re-enable the jenkins job `deploy-ci-app-catalog-next`

**Comment by woodt** [comment]
https://github.com/GSA/datagov-deploy/pull/1632

**Comment by woodt** [comment]
Molecule tests are working.  Currently testing in the sandbox environment.
Am running into a problem with the Python installation there and would like to confirm my hypothesis and proposed solution:

context: trying to run the catalog-web playbook against the catalog-next-web host.

problem: when creating the virtualenv for the catalog app, virtualenv fails with a "code for hash md5 not found."    Underlying problem is that `hashlib` can't be imported.

hypothesis: catalog-next-web is running bionic.  the sandbox hosts all want to use python 2.7.10, which I think is a little old for bionic.  (e.g., see https://github.com/saghul/pythonz/issues/141 )

proposal: can we switch to using Python 2.7.16 (say)?

**Comment by woodt** [comment]
I did a quick test on catalog-next-web and upgrading the Python version to 2.7.16 fixed the hashlib problem.  Question: how should I make this change permanent?  Do we want all the sandbox hosts tagged `v2` (for example) running the newer Python?  (In which case I could just add it to  `sandbox/group_vars/v2/vars.yml`)  Otherwise I can just bump the version for catalog-next-web

@adborden @mogul

**Comment by woodt** [comment]
Next step: we need to update the solr schema.  GIven the Python 2.7.16 version update, the catalog-next app actually starts up but fails because it can't locate a 2.8 Solr schema.

**Comment by adborden** [comment]
Added a reminder to re-enable the Jenkins job after we're done testing on sandbox.

**Comment by adborden** [comment]
@woodt re: python, I think this got left out when I setup the sandbox inventory. `v2` hosts are Bionic hosts and all should be configured with python 2.7.16 or newer. I would add [something like this](https://github.com/GSA/datagov-deploy/blob/1a488d7482dc6024156ae18afe826333bcb3cca4/ansible/inventories/production/group_vars/v2/vars.yml#L4) to sandbox.

**Comment by woodt** [comment]
Solr schema configuration for catalog-next at https://github.com/GSA/datagov-deploy-solr/pull/17

Playbook is now deploying catalog-next from GSA/catalog.data.gov to the sandbox.  New SOLR 2.8 core is in place.  CKAN db initialized (manually) via:

`paster --plugin=ckan db init -c /etc/ckan/production.ini`

CKAN is running, or at least passing a home page smoke test when run under `paster serve`.  Under the Apache mod_wsgi configuration, the process is segfaulting.  Still diagnosing.

**Comment by woodt** [comment]
Switched to using Apache as a reverse proxy and running catalog-next under gunicorn.  Seems to be working (after some consternation around getting the right HTTP headers to gunicorn.)

See https://catalog-next.sandbox.datagov.us

**Comment by woodt** [comment]
The last PR has been updated and is ready for re-review.

**Comment by woodt** [comment]
The main PR has been merged.  Waiting on a re-review of a change to the README.md, and then this can go into QA.

**Comment by woodt** [comment]
Ready for QA!

**Comment by adborden** [comment]
https://ci.sandbox.datagov.us/job/deploy-ci-app-catalog-next/10/console
