### ISSUE TITLE
Create CKAN extension for US metadata react app for inventory

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#327]
## User Story
As a developer, I want a repository for the metadata form code, so that we can have a decoupled front end 

(ckanext-inventorytheme)

## Acceptance Criteria
- [x] When I browse to (https://inventory.data.gov/dataset/new-metadata)
  THEN I see the react app loaded
- [x] WHEN I browse to https://inventory.data.gov/api/action/status_show
  THEN see the inventory theme extension is loaded

## Details/Tasks
- [x] Must work with [Inventory App](https://github.com/GSA/inventory-app)
- [x] CI using Inventory App
  - [x] Cypress tests
  - [x] Flake8
  - [ ] ~Code coverage~ see #365 
- [x] Add README.md
  - [x] README has section for Usage
  - [x] README has section for Development and Contributing
- [x] React APP in CKAN extension repoIt looks like the React source code is in a separate repo, we should move it into this repo
- [x] Add a Makefile or similar for running common tasks, these each should be a one-command target:

**Comment by starsinmypockets** [comment]
Depends on #328

**Comment by adborden** [comment]
@starsinmypockets here are my comments after reviewing https://github.com/GSA/ckanext-react_usmetadata. I think they're all in scope for this story but let me know if you feel any of this should be it's own chunk of work. I enabled the usual branch protections on the repo so additional comments will go into PR review like our usual process.

- At a high level, it should follow the same conventions as our other repos:
  - CircleCI instead of TravisCI
  - Markdown instead of RST
  - README docs should have sections for Usage, Development, and Contributing
- It looks like the React source code is in a separate repo, we should move it into this repo
- Add a Makefile or similar for running common tasks, these each should be a one-command target:
  - JS build steps
  - nosetests
  - codecov
  - linting with flake8
- Following the documentation does not seem to work:
  - Docs refer to yarn, but I'm not seeing any package.json or yarn.lock files
  - Docs refer to nosetest, but that doesn't seem to be declared as a dependency (or it's just not getting installed for me)
- Not sure if we should be using setup.py, poetry, or pipenv, but using requirements.txt seems wrong for an extension cc @woodt
- Maybe rename this to something like `ckanext-dcatus_metadata`, since this is really about DCAT-US metadata management and not React

**Comment by adborden** [comment]
The AC does not seem met and I'm seeing some open PRs, moving this back to Current Sprint.

**Comment by adborden** [comment]
https://inventory.sandbox.datagov.us/api/action/status_show shows the new dcat_metadata extension is enabled

New hello-world app is https://inventory.sandbox.datagov.us/dataset/new-metadata
