### ISSUE TITLE
Import harvest sources to staging

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#417]
## User story
As the dev team, I want to see my harvest sources on a staging site, so that I can test them and feel confident about harvesting on a production environment

## Acceptance criteria
- [x] When I go to the staging site
- [x] And I go to /harvests
- [x] And I choose a harvest type
- [x] Then I see the harvest sources listed in the source type tab in this document: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=264788117

**Comment by thejuliekramer** [comment]
@adborden We are seeing an error when trying to run import harvest sources script on staging `InternalError: (InternalError) cannot execute INSERT in a read-only transaction` - might be related to https://github.com/GSA/datagov-deploy/issues/488

<img width="1624" alt="Screen Shot 2020-09-08 at 11 43 10 AM" src="https://user-images.githubusercontent.com/7378770/92504968-01415200-f1c9-11ea-9ae5-9b77244774d8.png">

The same script was working for us in Sandbox

**Comment by thejuliekramer** [comment]
The above is fixed by using the admin- in front of the staging URL for API calls

**Comment by thejuliekramer** [comment]
@avdata99 the below error 'Please use Post Method' happens when we call https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/organization_show with {"id": "census-gov"} as the params 

However, we are already using a post here for this call: https://github.com/GSA/catalog.data.gov/blob/master/tools/harvest_source_import/remote_ckan/lib.py#L165

<img width="1018" alt="Screen Shot 2020-09-08 at 1 11 26 PM" src="https://user-images.githubusercontent.com/7378770/92512798-f8567d80-f1d4-11ea-8e64-e87032ad5037.png">

**Comment by thejuliekramer** [comment]
@jbrown-xentity we could use some guidance here. We are unable to interact with the CKAN api correctly at this moment. When we use the admin-catalog url we are redirected to catalog and get a 400 error, I tried from the admin, web and harvester hosts listed [here](https://github.com/GSA/datagov-deploy/blob/7b179ac6f7b01d28b2951d743ade3de8a3909172/ansible/inventories/staging/hosts) is there some other url for the api or server we should be using?

**Comment by thejuliekramer** [comment]
@hkdctol this is ready to QA. I sent you your login via Slack.  All daily updated harvest sources are already harvesting - the rest we need to run manually

**Comment by hkdctol** [comment]
Looks like the import of harvest sources to staging was successful. Will move to Done.
