### ISSUE TITLE
Save as draft

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#422]
# User Story
As a data publisher, I want to be able to save my work as a draft, so that I can come back to it later

# Implementation Details/Notes
- Clicking "save and continue" should save the dataset as a draft
- Clicking "save draft" should save the dataset as a draft as long as at least the title and owner organization are provided. The title is used to generate dataset name and URL.
- Draft datasets should be available at the user's profile (https://inventory.sandbox.datagov.us/user/(username))
- Unauthorized users should not be able to see draft datasets and should not see them listed on the `/dataset` page (CKAN default behaviour).
- Add "save as draft" button and move "save and continue button" as seen in these mock ups: https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297

# Acceptance Criteria
- [ ] WHEN I got to https://inventory.sandbox.datagov.us/dataset/new-metadata
- [ ]  AND I fill out a few (not all) required metadata fields
- [ ]  AND I click _save as draft_
- [ ]  AND if I am logged in
- [ ] ~~AND visit `/datasets`~~ (see implementation notes for details)
- [ ] THEN I can see my metadata saved in draft mode
- [ ] AND if I log out
- [ ] AND visit `/datasets`
- [ ] THEN I can _not_ see the saved metadata

**Comment by hkdctol** [comment]
@adborden do we need to add criteria to this ticket to account for the discussion we had today re saving drafts?

**Comment by adborden** [comment]
Good point. I think it's captured in the existing AC:
```
 AND if I log out
 AND visit /datasets
 THEN I can not see the saved metadata
```

**Comment by anuveyatsu** [comment]
@adborden We need to consider how to skip server-side validation when saving a dataset without all required metadata (save as a draft). We started looking at "USMetadata" extension to check how we can achieve it and discovered that there is already something for skipping validation:

https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L567-L581

From the code it looks like it's needed when cloning a dataset. See these 2 commits:

- Original implementation: https://github.com/GSA/USMetadata/commit/948653bb2debf20053630b559eb743fc72e8f6c4
- Improvement: https://github.com/GSA/USMetadata/commit/2bd1c66eb67e7bc46884f04ff7fa325e3aa7e4ef

We could re-use this for DCAT_USMetadata extension by adding "skip_validation" string into the title of a dataset when user needs to save it as a draft. However, having such string appended into the title might not be very user-friendly. We could also use any one of these more user-friendly (and cleaner options) by adding a new condition for disabling validation, examples:

- Add an "extra" metadata, eg, "skip_validation" which is a boolean.
- Disable validation for any datasets with state as "draft" so that server side validation is only done when publishing a dataset.

Note, users still must provide title (as we generate name from it) and owner organization to save a draft.

**Comment by adborden** [comment]
Can we move the validation logic from USMetadata to ckanext-dcat_usmetadata and drop USmetadata? That would give us full control over the metadata validation. From my perspective, ckanext-dcat_usmetadata should be replacing usmetadata.

I like the idea of just disabling validation on draft status, but I think users should still be warned if their draft metadata doesn't meet validation (but doesn't stop them from saving the draft).

**Comment by anuveyatsu** [comment]
@adborden 

> Can we move the validation logic from USMetadata to ckanext-dcat_usmetadata and drop USmetadata? That would give us full control over the metadata validation. From my perspective, ckanext-dcat_usmetadata should be replacing usmetadata.

We already do browser-side validation in 'dcat_usmetadata'. I'm not sure about what it takes to drop 'usmetadata' extension as we need to check and analyse what else it does. i.e. What other purpose does the 'usmetadata' extension have other than metadata validation?

For now, I suggest proceeding with an "extra" metadata, eg, "skip_validation" which is a boolean which will allow us to skip validation in 'usmetadata'. Later on we can we could analyse and estimate the work to move everything to the dcat extension.

> I like the idea of just disabling validation on draft status, but I think users should still be warned if their draft metadata doesn't meet validation (but doesn't stop them from saving the draft).

Yes, we should have some warning message but we need to discuss the flow, e.g., I imagine users click on 'save draft' button and they remain on the same metadata page but with some confirmation message + warning message.

**Comment by adborden** [comment]
> We already do browser-side validation in 'dcat_usmetadata'. I'm not sure about what it takes to drop 'usmetadata' extension as we need to check and analyse what else it does. i.e. What other purpose does the 'usmetadata' extension have other than metadata validation?

I'm not sure. USMetadata is doing similar things to what dcat_usmetadata should be doing: the dataset form for inputing DCAT-US, validation of DCAT-US metadata, and redactions (which we do not use). We should review the code to be sure there's nothing else. We can do that at a later time.

> For now, I suggest proceeding with an "extra" metadata, eg, "skip_validation" which is a boolean which will allow us to skip validation in 'usmetadata'. Later on, we could analyse and estimate the work to move everything to the dcat extension.
> 
> > I like the idea of just disabling validation on draft status, but I think users should still be warned if their draft metadata doesn't meet validation (but doesn't stop them from saving the draft).
> 
> Yes, we should have some warning message but we need to discuss the flow, e.g., I imagine users click on 'save draft' button and they remain on the same metadata page but with some confirmation message + warning message.

If we only validate on draft status, do we still need a skip_validation extra? Can we do it without the skip_validation extra?

**Comment by anuveyatsu** [comment]
@adborden at the moment, when user clicks on "Save and continue" button, we save it as a draft. If we disable validation on "draft" status, then we could use the following logic:

- When user clicks on "Save and continue", we save it as non-draft but private dataset so that it cannot b visible on the portal. It becomes "public" only when all 3 steps are completed.
  - Note this is different "private" property, this isn't from DCAT metadata spec.
- When user clicks on "Save draft" button, we save it as a draft so we don't do validation.

**Comment by adborden** [comment]
I think the draft status should be tied directly to the [CKAN private state](https://github.com/GSA/datagov-deploy/issues/2095). It's a bug that drafts are still visible in CKAN.

> * When user clicks on "Save and continue", we save it as non-draft but private dataset so that it cannot b visible on the portal. It becomes "public" only when all 3 steps are completed.
>   * Note this is different "private" property, this isn't from DCAT metadata spec.

"Save and continue" should save as draft and `private: true`. Only "Finish and publish" should change the state to non-draft and `private: false`.

I think in the Edit case, we're going to want to tweak the behavior. If the dataset is already published, then "Safe draft" doesn't make sense. I'm not sure we captured that in the Edit dataset story.

> * When user clicks on "Save draft" button, we save it as a draft so we don't do validation.

Right.

**Comment by anuveyatsu** [comment]
@adborden Drafts aren't visible in the CKAN afaik - only publisher can see it in the profile page. CKAN has 2 different concepts:

* **state**
  * active - regular dataset
  * draft - can be seen only by creator in the profile page (`/user/username`)
  * deleted - unlisted (cannot be seen or found). Only way to get this dataset is to inspect database.
* **visibility**
  * private - can be seen and found via search by  organization members to which a dataset belongs to
  * non-private (aka public) - can be seen and found by anyone

You're suggesting that:

* "Save and continue" => state: draft, visibility: private
* "Save draft" => state: draft, visibility: public (?)
* "Finish and publish" => state: active, visibility: public

I think we need to change this to:

* "Save and continue" => state: active, visibility: private
* "Save draft" => state: draft, visibility: private
* "Finish and publish" => state: activ, visibility: public

Note that both ways a dataset is private but has 2 different states - active vs draft.

Please, let me know what do you think.

**Comment by anuveyatsu** [comment]
Just flagging here that this issue might take more than 5 story points.

**Comment by adborden** [comment]
Is `visibility` it's own CKAN field, or is it the [private](https://docs.ckan.org/en/2.9/api/index.html) field that the behavior is based on? I don't think I've seen it before.

@anuveyatsu ah, I didn't realize CKAN had it's own concept of draft here. We'll need to dig into this a little. When I was referring to Draft, I was referring to the `publishing_status`, which I thought was a [USMetadata](https://github.com/GSA/USMetadata/blob/d3a138851f04a0d1aa5bb753452338299c8bf788/ckanext/usmetadata/plugin.py#L290)/[ckanext-datajson](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/plugin.py) concept.

It looks like there's a few bugs here with draft datasets.
1. Clicking "Export Drafts" does not include the draft dataset (#527).
1. There's no way to publish the draft dataset (#528).

I think we'll want to consider these in our discussion.

Maybe we can just ignore publish_status, I don't think there's a reason to keep it since it's tied to the old USMetadata model and we're not using the redaction feature.

Since `state: draft` is only visible to the user, then I think we want to be careful about how we communicate this status to users. The intention is that a Draft is visible within the organization, but not public. Maybe we don't even want to use CKAN's draft state since there's not a use case to have a dataset only visible to the one user who created it.

So, I think what we want something more like this:
- "Save and continue" => state: active, visibility: private (displayed as "Draft", takes you to the next screen)
- "Save draft" => state: active, visibility: private (displayed as "Draft", leaves you on the current screen)
- "Finish and publish" => state: active, visibility: public (displayed as "Published")

And then the Export Drafts button (#527), I guess we'd filter on `visibility: private`?

I think #528 will be resolved when we switch to the new resource form for editing (#502) because you could "Save and continue" then "Finish and publish" to publish without adding resources.

**Comment by adborden** [comment]
Ah, wait, I'm forgetting about https://github.com/GSA/datagov-deploy/issues/2314. Since inventory is a metadata repository, all datasets are considered `private: true` so that they are not visible to anonymous users. The exception is for data hosted on Inventory, which needs to be `private: false` so that the data resources are available to anonymous users. I think this means we need to keep track of the draft status separately, I guess with `publishing_status` after all.

@anuveyatsu maybe we can schedule a call to discuss.

**Comment by anuveyatsu** [comment]
@adborden I'm pasting our notes from the meeting so it can be kept in this thread for the future use:

## A new dataset

* "Save and continue"
  * state=active (eg, not yet active)
  * `private=true`
  * publishing_status=draft
  * do server-side validaiton
* "Save draft"
  * state=active
  * `private=true`
  * publishing_status=draft
  * don't do server-side validation
* "Finish and publish"
  * `private=true` (only if file upload => `private=false`)
  * publishing_status=published

Notes:

* Draft - not a CKAN's draft state but USMetadata's "publishing_status" field
* Disabling validaiton on USMetadata
  * Option 1: have an extra field, eg, "skip_validation".
  * Option 2: skip server-side validation at all and come back to it later
    * Only do validation on "Finish and publish". If any errors, then jump to related page (first one that have errors) and display error messages. 
  * Option 3: some string in a title, eg, "skip_validation"
  * Option 4: only validate fields that are filled... 

## Existing dataset

If `publishing_status` is "published", then we just hide "Save draft" button and the datast remains "published" after user applies any modifications in metadata.

## Exporting draft datasets

https://github.com/GSA/datagov-ckan-multi/issues/527 - should be fixed once this issue is fixed.
