### ISSUE TITLE
display clear and well formatted error messages from the server

### ISSUE THREAD

**Issue by osahon-okungbowa** [GSA/datagov-ckan-multi#434]
## User Story
As a data publisher, when submit a new datset, if I made an error, I'd like a useful error message, so that I can submit my data correctly

## Implementation Notes
- API is currently returning a help message in useful human-readable language, so we should display that
- Change validation message for license field to indicate a selection is required
- Show help field from CKAN error response as the error message for non-specific error
- Non-200 server response help text is clearly formatted as alerts
- The following server messages/error are clearly communicated to the user:
  - Authentication failure
  - Non-unique name / URL value
  - Non-unique Unique ID field

### Acceptance Criteria
- [ ] When I submit a duplicate titled dataset or a duplicate unique ID
- [ ] Then I should see a message that says

**Comment by kimwdavidson** [comment]
Kim to update acceptance criteria based on existing error messages

**Comment by anuveyatsu** [comment]
Some notes about this ticket:

* `USMetadata` extension doesn't validate if "Unique ID" field value is actually unique.
* Afaik, it is done for purpose so that publishers from different offices can have same unique ids.
* I can see that there is a `TODO` comment in the code of `USMetadata` here that states: "should this unique_id be validated against any other unique IDs for this agency?"
  * https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L116
* I can also see that there is a validator function that checks if the `unique_id` field is unique within the CKAN organization.
