### ISSUE TITLE
Review critical issues in catalog-next harvesting

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#448]
## User Story

As the catalog dev team, we want to know which of the harvest issues to address on staging and which should be addressed on production, so that we can use our time and resources appropriately.

(https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=1225846146) 

## Acceptance Criteria
- [ ] 

## Details / tasks
- [ ] Add a column to the spreadsheet for noting whether this is possibly an environment issue vs. a bug
- [ ] Review each "needs" work harvest and note whether these are likely environment issues or bugs

**Comment by thejuliekramer** [comment]
Update: I went through each 'needs work' row of the spreadsheet and categorized them as:

1. 'timeout' - meaning the job does not complete in the 1 days provided
2. 'same error as production' - meaning there is an error - but the same error is happening in prod so it is not specific to staging
3.  'No Records Error Not really an error" - this 'no records' error is logged as an error but it just means there are no new records to update. This code is not in production so that is why we are not seeing the error there

We were seeing some other errors related to getting the JSON object but those were all fixed when we purged the queues and ran the harvest again

**Comment by thejuliekramer** [comment]
Since clearing the queues I have noticed a couple of the sources previously timing out are now finishing - so I am going to run through these marked as timeout one more time to see if there are any issues with them other than timeouts

**Comment by avdata99** [comment]
About _timeouts_ I created and [issue](https://github.com/ckan/ckanext-harvest/issues/417) and a [PR](https://github.com/ckan/ckanext-harvest/pulls/418) to allow really long jobs without increasing the timeout.

**Comment by thejuliekramer** [comment]
After restarting the queues - the previous timeouts are now working.

Overall there are no unique errors to the staging environment.
