### ISSUE TITLE
Bug editing previous page of form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#514]
## To reproduce:
- Add a new dataset
- Fill out the required fields
- Click to save and continue
- Click the Required Metadata tab in the top navigation
- Change a value
- Click to save

Expected behavior: saves changes
Observed behavior: white screen

This may be fixed by #455 ?

**Comment by anuveyatsu** [comment]
This issue will be fixed in [this pull request](https://github.com/GSA/ckanext-dcat_usmetadata/pull/156). Some things to note:

- When going back and editing the form, we cannot edit/save:
  - "title" of the dataset;
  - "description" of the dataset.

Users still can go back and forward without any errors, however, saving these 2 fields are out of this issue's scope and should be considered in https://github.com/GSA/datagov-ckan-multi/issues/455

**Comment by hkdctol** [comment]
Confirmed on sandbox I can go back to previous page and edit an element that is not title or description.
