### ISSUE TITLE
Research and Analysis re harvesting etc

### ISSUE THREAD

**Issue by akariv** [GSA/datagov-ckan-multi#63]
https://github.com/ViderumGlobal/PM-datagov/issues/15

**Comment by rufuspollock** [comment]
Closing this as complete. This issue was created in April and the initial research on this was done in April and May leading up to the meeting on May 23.

Work included

* [x] research and analysis of existing data.gov CKAN setup
* [ ] research and analysis of current CKAN harvesting approach and current state 
* [x] research and analysis of existing data.gov harvesting setup both at the general level and code details
