### ISSUE TITLE
 Test case: DOE combining 3 data.json sources w/ current implementation

### ISSUE THREAD

**Issue by JJediny** [GSA/datagov-ckan-multi#93]
There are 3 data.json sources a test user is looking to combine and to test out using the multi-tenant product to harvest from and download the consolidated data.json post harvest:
- [ ] https://energy.gov/data.json
- [ ] https://openei.org/data.json
- [ ] https://www.archive.arm.gov/metadata/data.json

**Comment by akariv** [comment]
From analyzing this issue I got:
- There was a logging problem in the ckan pods (the formatting string was misconfigured which prevented logs from being emitted). 
I fixed in ckan-cloud-helm (and released version 0.0.8) and datagov-ckan-provisioning-api to use this version. Also redeployed the provisioning app and I updated the relevant ckan instance.
After updating logging works as well as harvesting (https://ckan-cloud-energy-test-5d2e3395.datagov.us/dataset).
I suspect there might be an initialization issue here that might be the problem, but I suggest we open that in a separate issue.

**Comment by adborden** [comment]
@akariv thanks for looking into this. Still trying to figure out how everything fits together, so I've got some questions for ya:

I saw https://github.com/ViderumGlobal/datagov-ckan-cloud-provisioning-api/commit/2ab41508726b9ffe5cf859a19670f61cca815ccf but how does that get deployed? Is that a manual command, or running a job in Jenkins, or something else?

Can you elaborate on the initialization issue?

BTW, please use pull requests in the future so notifications are generated.

**Comment by akariv** [comment]
@adborden

This is manually deployed at the moment, no CI or Jenkins job.
In fact, the k8s cluster is using the 'latest' tag on the image so deleting
the provisioning api pod is sufficient for redeploying.
This app is deployed using CCO, so the 'correct' way to deploy (without pod
deletion hacks) would be to edit the app spec in cco and change the image
tag to the latest hash.
(i.e. something like `ckan-cloud-operator app edit provisioning-.....` and
update it there).

(and will do re PRs)

**Comment by adborden** [comment]
This looks good, thanks!
