### ISSUE TITLE
Notify CKAN Admins Via Email Service

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#97]
## User Story

We are generating an email per issue #82, we need to now send it via a third party email service

## Details / tasks
- [ ] Decide on what email service
- [ ] Send email

**Comment by rufuspollock** [comment]
I don't think we want to notify via email per harvest error. We want to log locally and then push those into CKAN metastore or another log analysis environment (the latter may be better in fact).

**Comment by kimwdavidson** [comment]
CKAN already has a way for harvesters to report errors, including an email service, so we should either integrate with that system or create a new one

**Comment by kimwdavidson** [comment]
@avdata99 to send example error report to @adborden

**Comment by avdata99** [comment]
@adborden we wrote a very simple (and customizable vía CSS) [template report].(https://gitlab.com/datopian/ckan-ng-harvest/blob/master/libs/harvester/templates/harvest-report.html)
At the moment the template has no CSS since I'm not the best for this kind of job but maybe it would be easy to do.

Maybe could be useful for use as a final harvest report or modify to send via email.

![sample-harvest-report](https://user-images.githubusercontent.com/3237309/64545746-af3cc680-d2ff-11e9-9287-324275e7ab94.png)

**Comment by adborden** [comment]
On Mon, 2019-09-09 at 08:49 -0700, Andres Vazquez <notifications@github.com> wrote:
> @adborden we wrote a very simple (and customizable vía CSS) [template report].(https://gitlab.com/datopian/ckan-ng-harvest/blob/master/libs/harvester/templates/harvest-report.html)
> At the moment the template has no CSS since I'm not the best for this kind of job but maybe it would be easy to do.
> 
> Maybe could be useful for use as a final harvest report or modify to send via email.
> 
> ![sample-harvest-report](https://user-images.githubusercontent.com/3237309/64545746-af3cc680-d2ff-11e9-9287-324275e7ab94.png)

I'm looking an example report so that I can see the type of errors that
need reporting. For example, schema validation errors, or are they
network errors trying to fetch resources?

I'm not so interested in the visuals, just the content.

--
Aaron D Borden
Human and hacker

**Comment by avdata99** [comment]
Ok,behind the report there is a full JSON data about the harvest process. 
We can connect this data with any other destination.
We include schema validation error and also network errors (for example 404 trying to get data.json files). We can improve the resource if necessary.

**Comment by avdata99** [comment]
Yes @adborden, here some example for harvest data.json from _Railroad Retirement Boar_.

https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/harvest/datajson/samples/sample-RRB-final-results.json

This file includes all datasets, resources, [errors](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/harvest/datajson/samples/sample-RRB-final-results.json#L1974) and warnings.

This file shows error with my local CKAN instance that is no real errors. Also this file is still subject to change but is a good example of what we are working on.
